### ISSUE TITLE
Exception while parsing Vkontakte page

### ISSUE THREAD

**Issue by akamaus** [ruippeixotog/scala-scraper#10]
Hello! 
I'm trying to use the library to parse Vkontakte (Russian social network) community page. At first grabber was redirected to mobile version, but after I implemented the trick described in ticket #5 I got the following behavior:
```
[info] Running grabber.Runner 
[error] (run-main-0) java.util.NoSuchElementException: head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420)
	at scala.collection.immutable.Nil$.head(List.scala:417)
	at net.ruippeixotog.scalascraper.browser.Browser$$anonfun$4.apply(Browser.scala:50)
	at net.ruippeixotog.scalascraper.browser.Browser$$anonfun$4.apply(Browser.scala:49)
	at scala.Option.map(Option.scala:146)
	at net.ruippeixotog.scalascraper.browser.Browser.net$ruippeixotog$scalascraper$browser$Browser$$process(Browser.scala:49)
	at net.ruippeixotog.scalascraper.browser.Browser$$anonfun$3.apply(Browser.scala:39)
	at net.ruippeixotog.scalascraper.browser.Browser$$anonfun$3.apply(Browser.scala:39)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at net.ruippeixotog.scalascraper.browser.Browser.get(Browser.scala:17)
	at grabber.Runner$.delayedEndpoint$grabber$Runner$1(grabber.scala:11)
	at grabber.Runner$delayedInit$body.apply(grabber.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at grabber.Runner$.main(grabber.scala:6)
	at grabber.Runner.main(grabber.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

Code snippet I used:

```scala
package grabber

import net.ruippeixotog.scalascraper.browser.Browser
import org.jsoup.{ Connection, Jsoup }

object Runner extends App {
  val browser = new Browser {
    override def requestSettings(conn: Connection) = conn.userAgent("Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:27.0) Gecko/20100101 Firefox/27.0")
  }

  val doc = browser.get("http://vk.com/scala_lang")
  print(doc)
}
```

build.sbt:
```
name := "vkgazer"
version := "0.1"
scalaVersion := "2.11.7"
libraryDependencies += "net.ruippeixotog" %% "scala-scraper" % "0.1.1"
libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.4" % "test"
```

**Comment by ruippeixotog** [comment]
Hi @akamaus! That happened because of a bug I already fixed in b78859a. Since then I did not release any non-snapshot version, so I have just released v0.1.2 in order for you to use it (the changes since v0.1.1 were mostly bugfixes and dependency updates anyway). Please try it and see if it solves your problem.

**Comment by akamaus** [comment]
Thanks for a prompt reply! 
I changed scala-scraper version to 0.1.2 in build.sbt and definitely made some progress. Looks like I just need to further tweak http headers to make VK server happy. Now I'm getting MalformedUrl exception now, though. Looks like erroneous reaction to redirect or something like that:
```
 Hello[error] (run-main-0) java.lang.IllegalArgumentException: Malformed URL: /badbrowser.php
java.lang.IllegalArgumentException: Malformed URL: /badbrowser.php
	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:78)
	at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:38)
	at org.jsoup.Jsoup.connect(Jsoup.java:73)
	at net.ruippeixotog.scalascraper.browser.Browser.get(Browser.scala:20)
	at net.ruippeixotog.scalascraper.browser.Browser.processResponse(Browser.scala:60)
	at net.ruippeixotog.scalascraper.browser.Browser$$anonfun$5.apply(Browser.scala:65)
	at net.ruippeixotog.scalascraper.browser.Browser$$anonfun$5.apply(Browser.scala:65)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at net.ruippeixotog.scalascraper.browser.Browser.get(Browser.scala:20)
	at grabber.Runner1$.delayedEndpoint$grabber$Runner1$1(grabber.scala:11)
	at grabber.Runner1$delayedInit$body.apply(grabber.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at grabber.Runner1$.main(grabber.scala:6)
	at grabber.Runner1.main(grabber.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
Caused by: java.net.MalformedURLException: no protocol: /badbrowser.php
	at java.net.URL.<init>(URL.java:585)
	at java.net.URL.<init>(URL.java:482)
	at java.net.URL.<init>(URL.java:431)
	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:76)
	at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:38)
	at org.jsoup.Jsoup.connect(Jsoup.java:73)
	at net.ruippeixotog.scalascraper.browser.Browser.get(Browser.scala:20)
	at net.ruippeixotog.scalascraper.browser.Browser.processResponse(Browser.scala:60)
	at net.ruippeixotog.scalascraper.browser.Browser$$anonfun$5.apply(Browser.scala:65)
	at net.ruippeixotog.scalascraper.browser.Browser$$anonfun$5.apply(Browser.scala:65)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at net.ruippeixotog.scalascraper.browser.Browser.get(Browser.scala:20)
	at grabber.Runner1$.delayedEndpoint$grabber$Runner1$1(grabber.scala:11)
	at grabber.Runner1$delayedInit$body.apply(grabber.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at grabber.Runner1$.main(grabber.scala:6)
	at grabber.Runner1.main(grabber.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by akamaus** [comment]
I inspected traffic with wireshark and found this:
```
<noscript><meta http-equiv="refresh" content="0; URL=/badbrowser.php"></noscript>\n
```
Probably parser rules need to be relaxed a bit or some error-ignoring mode needs to be activated.

**Comment by ruippeixotog** [comment]
Hmm... I guess this highlights why I shouldn't be parsing and interpreting HTML in any way unless I was using a full browser implementation.

Interpreting the `<meta>` refresh directive was something of a nice-to-have, a way to emulate at least the redirections done by a browser. Following `Location` headers in HTTP 3xx responses is easy enough and doesn't require heavy parsing logic (it doesn't involve interpreting HTML at all). However, following the meta refresh redirects is another matter completely. It involves:

* Parsing the `content` tag attribute in a very specific way (handling multiple key-values, quoting, escaping, case insensitivity...);
* Handing the URL as a browser would do (with full paths, paths starting with "/" and relative paths);
* Analyzing the context in which the tag appears (if they are inside `<script>`/`<noscript>` tags).

Right now, only the first one is being done and in a very adhoc way, not coming even close to support the full spec.

I'm inclined to drop the handling of `<meta>` redirects at all and making it the responsibility of the user to be aware of them and possibly point the `Browser` request directly to the target address of the redirection (nowadays redirecting this way is not very common anyway). I guess that would solve your problem too, wouldn't it?

**Comment by akamaus** [comment]
Well, at first I tempted to say you should at least leave a possibility for user to decide. But, you're right, redirects are usually implemented with http 30[12] code and Location header. And I feel it's better to be simplistic than to pretend being smart but actually do the wrong thing.

I solved my immediate problem with #11, but day passed and I'm unhappy with solution. I agree that dropping any mentions of `<meta>` is a simplest least-confusing way. For my scraping needs I will be happy if http30x are supported. Maybe it's worth to make it a default  optional easily configurable behavior, like setting UserAgent. I Don't think it a good idea to make library user grok underlying jsoup library just to do such a basic thing.

**Comment by ruippeixotog** [comment]
I have just removed the support for meta refresh redirections (f74d7af) and added support for specifying the user agent as the `Browser` is created (49ec348).

**Comment by akamaus** [comment]
Works nicely for me, thanks! I have some doubts about putting userAgent in constructor argument though. Just pretend in future you also decide to ease adding cookies. Why don't we make, say, addCookie and setUserAgent methods? Seems to me that would be more homogeneous.
